In [16]:
import pandas as pd
import numpy as np


1. ¿Qué diferencia hay entre una Serie y un DataFrame?

# La estructura. Un serie es unidimensional y un dataframe es bidimensional

2. Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [3]:
valores = [1, 3, 5, 7, 9, 11, 13]
indices = ["L", "M", "X", "J", "V", "S", "D"]

3. A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [4]:
serie = pd.Series(valores, index=indices)
print(serie)

L     1
M     3
X     5
J     7
V     9
S    11
D    13
dtype: int64


4. A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.

In [5]:
diccionario1 = {}
for indice, valor in zip(indices, valores):
    diccionario1[indice] = valor

print(diccionario1)

{'L': 1, 'M': 3, 'X': 5, 'J': 7, 'V': 9, 'S': 11, 'D': 13}


5. Crea una Serie con el diccionario creado en el punto anterior.

In [9]:
serie2 = pd.Series(diccionario1)
print(serie2)

L     1
M     3
X     5
J     7
V     9
S    11
D    13
dtype: int64



6. ¿Qué forma tiene esta última Serie?

In [8]:
serie2.shape

(7,)


7. ¿Qué tamaño tiene?

In [10]:
serie2.size

7

8. ¿Cuáles son los índices de la Serie?

In [11]:
serie2.index

Index(['L', 'M', 'X', 'J', 'V', 'S', 'D'], dtype='object')

9. ¿Y los values?

In [12]:
serie2.values

array([ 1,  3,  5,  7,  9, 11, 13], dtype=int64)

10. Extrae el valor para el índice "lunes"

In [13]:
serie2["L"]

1

11. Extrae el valor para el índice "lunes", "martes" y "miércoles".


In [14]:
print(serie2["L"])
print(serie2["M"])
print(serie2["X"])

1
3
5


12. Extrae el valor para el índice "lunes" y "domingo".

In [15]:
serie2[0]
serie2[6]

13


Es el turno de los DataFrames

13. Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [17]:
array1 = np.random.randint(1, 12, (4, 3))
print(array1)

[[11  1  4]
 [ 8  8  8]
 [ 5  5  5]
 [ 7  4  5]]


14. Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [18]:
pd.DataFrame(array1, columns=["España", "Francia", "Italia"])

España  Francia  Italia
0      11        1       4
1       8        8       8
2       5        5       5
3       7        4       5

15. Descarga el archivo "medallas" y carga el DataFrame.

In [21]:
df_medallas = pd.read_csv("medallas.csv", index_col=0)
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

16. Usando el loc extrae todas las columnas de la fila de Tailandia.

In [22]:
Tai = df_medallas.loc[1, :]
print(Tai)

País      China
Oro        1473
Plata       994
Bronce      720
Name: 1, dtype: object


17. Usando el loc extrae todas las columnas de China e Irán.

In [23]:
Chi_Ira = df_medallas.loc[(df_medallas.index == 1) | (df_medallas.index == 4), :]
print(Chi_Ira)

    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197


18. Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [24]:
Chi_Ira2 = df_medallas.loc[
    (df_medallas.index == 1) | (df_medallas.index == 4), ["Oro", "Plata", "Bronce"]
]
print(Chi_Ira2)

    Oro  Plata  Bronce
1  1473    994     720
4   179    181     197


19. Usando el iloc extrae la información de la India. Devolved todas las columnas.

In [25]:
Ind = df_medallas.iloc[5, :]
print(Ind)

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object


20. Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [26]:
impares = df_medallas.iloc[1::2, :]
print(impares)

               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235


21. Utilizando el código del ejercicio anterior,selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [27]:
impares2 = impares.iloc[:, 1:4]
print(impares2)

print(df_medallas)

     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235
               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235


23. Contesta a las siguientes preguntas:
¿Qué país consiguió más de 200 medallas de oro?

In [28]:
paises_oro = df_medallas.loc[df_medallas["Oro"] > 200]
print(paises_oro)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827


24. ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

In [29]:
paises_oroyplata = df_medallas.loc[(df_medallas["Oro"] > 200) & (df_medallas["Plata"] > 1000)]
print(paises_oroyplata)

    País   Oro  Plata  Bronce
2  Japón  1032   1037     985


25. ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [30]:
paises_oroybronce = df_medallas.loc[(df_medallas["Oro"] > 200) & (df_medallas["Bronce"] > 700)]
print(paises_oroybronce)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827


26. Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [31]:
df_medallas["Total"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]
df_medallas

País   Oro  Plata  Bronce  Total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446