In [3]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array1 = np.random.randint(10, 100, 50)
array1

print(array1[::5])

[77 46 56 51 98 56 78 37 12 74]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
array2 = np.random.randint(1, 21, 30)
array2

print(array2[1::2])

[18  7 19 11 19 12 18  8  6 10 16 17  2 14 11]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [5]:
array_3 = np.empty((4, 6)).round(2) + 4
print(array_3[-1])

[4. 4. 4. 4. 4. 4.]


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.


In [6]:
array_4 = np.random.rand(6, 4).round(2)
print(array_4)

print(array_4[0:6, 1])

[[0.04 0.92 0.59 0.68]
 [0.24 0.41 0.75 0.07]
 [0.97 0.86 0.35 0.18]
 [0.79 0.78 0.07 0.64]
 [0.56 0.51 0.47 0.24]
 [0.1  0.55 0.07 0.39]]
[0.92 0.41 0.86 0.78 0.51 0.55]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [7]:
array_5 = np.random.randint(-50, 50, size=30)
print(array_5)
np.where(array_5 < 0, "negativo", "positivo")
array_5[array_5 < 0]

[ 46  27 -50 -35  36  -5   9  22 -15  -8 -50  26  24 -42  15  34 -21 -29
 -39 -17 -35   8 -37 -38  13 -19  39  17 -32  28]


array([-50, -35,  -5, -15,  -8, -50, -42, -21, -29, -39, -17, -35, -37,
       -38, -19, -32])

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [8]:
array_6 = np.random.rand(10).round(2)
print(array_6)
posiciones = array_6[array_6 > 0.5]
print(posiciones)
posiciones2 = np.where(array_6 > 0.5)
print(posiciones2)

[0.14 0.79 0.13 0.05 0.46 0.11 0.66 0.46 0.92 0.7 ]
[0.79 0.66 0.92 0.7 ]
(array([1, 6, 8, 9], dtype=int64),)


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [9]:
array_7 = np.arange(1, 101)[:40]
elementos_divisibles = array_7[(array_7 % 3 == 0) & (array_7 % 4 == 0)]

print(array_7)
print(elementos_divisibles)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[12 24 36]


8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [10]:
array_3 = np.random.randint(1, 101, size=(2, 3, 4))
print(array_3)

array_2 = array_3.reshape((2, -1))
print(array_2)

[[[55 23 67 78]
  [94 74 11 10]
  [70 47 92 57]]

 [[80 29 41 78]
  [72 93  8 40]
  [71 74 86 29]]]
[[55 23 67 78 94 74 11 10 70 47 92 57]
 [80 29 41 78 72 93  8 40 71 74 86 29]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [11]:
array_7 = np.arange(1, 61).reshape(3, 4, 5)
print(array_7)
array_7_reshape = np.reshape(array_7, (2, 30))

# tener en cuenta el n de valores para la dimesion nueva
print(array_7_reshape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
  55 56 57 58 59 60]]


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [12]:
array_3 = np.random.rand(4, 3, 2)
print(array_3)
array_2 = array_3.reshape((4, -1))
print(array_2)

[[[0.24067876 0.05585396]
  [0.86810534 0.90481016]
  [0.68812959 0.2798366 ]]

 [[0.77019878 0.6259421 ]
  [0.0980849  0.3661852 ]
  [0.08211321 0.25678392]]

 [[0.92607835 0.40030613]
  [0.33299553 0.51971955]
  [0.90977558 0.69921797]]

 [[0.33920327 0.82977439]
  [0.50934768 0.02795586]
  [0.8601631  0.40279944]]]
[[0.24067876 0.05585396 0.86810534 0.90481016 0.68812959 0.2798366 ]
 [0.77019878 0.6259421  0.0980849  0.3661852  0.08211321 0.25678392]
 [0.92607835 0.40030613 0.33299553 0.51971955 0.90977558 0.69921797]
 [0.33920327 0.82977439 0.50934768 0.02795586 0.8601631  0.40279944]]


Ejercicios con transpose:

1. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [13]:
array_7 = np.arange(1, 61).reshape(3, 4, 5)
print(array_7)

array_7_transpose = np.transpose(array_7, (2, 1, 0))
print(array_7)
print(array_7_transpose)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


5. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [14]:
array_3 = np.random.rand(4, 3, 2)
print(array_3)
array_transpose = np.transpose(array_3, (1, 2, 0))
print(array_transpose)

[[[8.01784516e-01 4.90236931e-01]
  [3.16410150e-01 5.35553960e-02]
  [5.85107558e-01 2.28141895e-01]]

 [[8.94954208e-01 5.05331786e-01]
  [5.69799263e-01 1.63817996e-02]
  [7.24169645e-01 2.27942566e-01]]

 [[5.05909162e-01 7.98463188e-01]
  [2.07115501e-01 5.33386106e-01]
  [6.32333176e-05 3.63571541e-01]]

 [[2.00188034e-01 2.63883171e-01]
  [7.79901268e-01 9.39472037e-01]
  [8.92642183e-03 1.90977042e-01]]]
[[[8.01784516e-01 8.94954208e-01 5.05909162e-01 2.00188034e-01]
  [4.90236931e-01 5.05331786e-01 7.98463188e-01 2.63883171e-01]]

 [[3.16410150e-01 5.69799263e-01 2.07115501e-01 7.79901268e-01]
  [5.35553960e-02 1.63817996e-02 5.33386106e-01 9.39472037e-01]]

 [[5.85107558e-01 7.24169645e-01 6.32333176e-05 8.92642183e-03]
  [2.28141895e-01 2.27942566e-01 3.63571541e-01 1.90977042e-01]]]


Preguntas teóricas:

1. ¿Qué diferencia existe entre el reshape y el transpose?
reshape cambia la forma del array y transpose transpone las dimensiones del array

2. ¿Y entre el transpose y el swapaxes?
swapaxes intercambia dos ejes pero no puedes especificar el orden, con transpose sí puedes



Funciones Aritméticas y Estadísticas

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [15]:
array_8 = np.random.rand(2, 3, 5).round(1)
array_8

array([[[0.7, 0.5, 0. , 0.4, 0.5],
        [0.7, 0.7, 0.8, 0.5, 0.1],
        [0.7, 0.1, 0.1, 0.9, 0.3]],

       [[0.4, 1. , 0.9, 0.7, 0.5],
        [0.2, 1. , 1. , 0.1, 0.3],
        [0.6, 1. , 0.3, 0.5, 0.8]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".