In [2]:
import pandas as pd

In [ ]:
# 1. ¿Qué diferencia hay entre una Serie y un DataFrame?
# La estructura. Un serie es unidimensional y un dataframe es bidimensional

In [3]:
# 2. Momento de trabajar con Series. Contesta a las siguientes preguntas:
# Crea dos listas:
# Una que se llame "valores" que tenga 7 números aleatorios.
valores = [1, 3, 5, 7, 9, 11, 13]
# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.
indices = ["L", "M", "X", "J", "V", "S", "D"]

In [5]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y 
# la variable indices sean los índices de la Serie.
serie = pd.Series(valores, index=indices)
print(serie)

L     1
M     3
X     5
J     7
V     9
S    11
D    13
dtype: int64


In [8]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for.
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.
diccionario1 = {}
for indice, valor in zip(indices, valores):
    diccionario1[indice]=valor

print(diccionario1)

{'L': 1, 'M': 3, 'X': 5, 'J': 7, 'V': 9, 'S': 11, 'D': 13}


In [10]:
# Crea una Serie con el diccionario creado en el punto anterior.
serie2 = pd.Series(diccionario1)
print(serie2)

L     1
M     3
X     5
J     7
V     9
S    11
D    13
dtype: int64


In [17]:
# ¿Qué forma tiene esta última Serie?
serie2.shape

(7,)

In [12]:
# ¿Qué tipo de datos tiene?
serie2.dtype

dtype('int64')

In [13]:
# ¿Qué tamaño tiene?
serie2.size

7

In [14]:
# ¿Cuáles son los índices de la Serie?
serie2.index

Index(['L', 'M', 'X', 'J', 'V', 'S', 'D'], dtype='object')

In [15]:
# ¿Y los values?
serie2.values

array([ 1,  3,  5,  7,  9, 11, 13])

In [22]:
# Extrae el valor para el índice "lunes"
serie2["L"]

1

In [26]:
# Extrae el valor para el índice "lunes", "martes" y "miércoles".
print(serie2["L"])
print(serie2["M"])
print(serie2["X"])

1
3
5


In [29]:
# Extrae el valor para el índice "lunes" y "domingo".
serie2[0]
serie2[6]

13

In [30]:
import numpy as np

In [33]:
# 3. Es el turno de los DataFrames
# Crea un array de dos dimensiones con 4 filas y 3 columnas.
array1 = np.random.randint(1,12, (4,3))
print(array1)

[[ 7  2 10]
 [10  9  5]
 [ 2  5  1]
 [ 7  1  7]]


In [34]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
pd.DataFrame(array1, columns=["España", "Francia", "Italia"])

España  Francia  Italia
0       7        2      10
1      10        9       5
2       2        5       1
3       7        1       7

In [41]:
# Descarga el archivo "medallas" y carga el DataFrame.
df_medallas = pd.read_csv("medallas.csv", index_col=0)
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [51]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.
Tai = df_medallas.loc[1, :]
print(Tai)

País      China
Oro        1473
Plata       994
Bronce      720
Name: 1, dtype: object


In [52]:
# Usando el loc extrae todas las columnas de China e Irán.
Chi_Ira = df_medallas.loc[(df_medallas.index == 1) | (df_medallas.index == 4), :]
print(Chi_Ira)

    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197


In [53]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
Chi_Ira2 = df_medallas.loc[(df_medallas.index == 1) | (df_medallas.index == 4), ["Oro", "Plata", "Bronce"]]
print(Chi_Ira2)

    Oro  Plata  Bronce
1  1473    994     720
4   179    181     197


In [55]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.
Ind = df_medallas.iloc[5, :]
print(Ind)

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object


In [59]:
# Usando el iloc extrae todas las columnas de los paises que estén en posición impar.
# La primera que nos tendría que salir es Japón y la última Corea del Norte.
impares = df_medallas.iloc[1::2, :]
print(impares)


               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235


In [63]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
impares2 = impares.iloc[:, 1:4]
print(impares2)

     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235


In [65]:
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [64]:
# Contesta a las siguientes preguntas:
# ¿Qué país consiguió más de 200 medallas de oro?
paises_oro = df_medallas.loc[df_medallas["Oro"]>200]
print(paises_oro)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827


In [68]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
paises_oroyplata = df_medallas.loc[(df_medallas["Oro"]>200) & (df_medallas["Plata"]>1000)]
print(paises_oroyplata)

    País   Oro  Plata  Bronce
2  Japón  1032   1037     985


In [69]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
paises_oroybronce = df_medallas.loc[(df_medallas["Oro"]>200) & (df_medallas["Bronce"]>700)]
print(paises_oroybronce)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827


In [70]:
# Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.
df_medallas["Total"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]
df_medallas

País   Oro  Plata  Bronce  Total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446