In [3]:
import numpy as np

Creación y Indexación:

In [4]:
# 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

# Crear un array 1D con 50 valores aleatorios del 10 al 99
array_1 = np.random.randint(10, 100, size=50)

# Acceder a los elementos en las posiciones múltiplos de 5 
elementos_multiplos_de_5 = array_1[4::5]

print("Array completo:")
print(array_1)
print("\nElementos en posiciones múltiplos de 5:")
print(elementos_multiplos_de_5)


Array completo:
[35 75 36 60 98 23 77 74 20 13 97 49 89 54 22 94 86 38 22 33 13 96 35 18
 18 85 92 36 54 47 11 90 99 89 78 67 66 35 78 90 84 73 29 48 62 77 62 94
 73 85]

Elementos en posiciones múltiplos de 5:
[98 13 22 33 18 47 78 90 62 85]


In [5]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

array_2 = np.random.randint(0, 21, size=30)
print(array_2)
posicion_impar= array_2[1::2]
print(posicion_impar)

[ 4  8  3 13 14  5 10  4 18 13  4  3  3  7  8 18 16  1  9 19 18  4  4 15
  7 16  9 19  2 19]
[ 8 13  5  4 13  3  7 18  1 19  4 15 16 19 19]


In [6]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array_3 = np.empty((4,6)).round(2) + 4
print(array_3[-1])


[4. 4. 4. 4. 4. 4.]


In [7]:
# 4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. 
# Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

array_4 = np.random.rand(6,4).round(2)
print(array_4)
print(array_4[0:6,1])



[[0.27 0.14 0.18 0.37]
 [0.08 0.28 0.65 0.54]
 [0.02 0.42 0.19 0.49]
 [0.22 0.22 0.08 0.5 ]
 [0.8  0.66 0.3  0.06]
 [0.59 0.07 0.55 0.75]]
[0.14 0.28 0.42 0.22 0.66 0.07]


In [8]:
# 5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
array_5 = np.random.randint(-50, 50, size=30)
print(array_5)
np.where(array_5 < 0, 'negativo', 'positivo')
array_5[array_5<0]

[-49   1  42 -43  43  13 -19 -22 -46  35   4  31  -6  23 -46 -40  41   4
   9 -16  47  35  37 -26 -41   4   4 -19  31  47]


array([-49, -43, -19, -22, -46,  -6, -46, -40, -16, -26, -41, -19])

In [20]:
# 6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. 
# ¿En que posición/es están esos elementos?
array_6 = np.random.rand(10).round(2)
print(array_6)
posiciones = array_6[array_6>0.5]
print(posiciones)
posiciones2 = np.where(array_6>0.5)
print(posiciones2)

[0.03 0.97 0.77 0.66 0.04 0.91 0.36 0.21 0.59 0.39]
[0.97 0.77 0.66 0.91 0.59]
(array([1, 2, 3, 5, 8]),)


In [ ]:
#7. 

In [10]:
# 8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). 
# Reemplaza los elementos en posiciones múltiplos de 3 por 0. AMBAS

Ejercicios con reshape

In [ ]:
#1.

In [32]:
# 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). 
# Utiliza reshape para convertirlo en un array 2D.
array_7 = np.arange(1, 61).reshape(3, 4, 5)
print(array_7)
array_7_reshape = np.reshape(array_7, (2, 30)) #tener en cuenta el n de valores para la dimesion nueva
print(array_7_reshape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
  55 56 57 58 59 60]]


In [ ]:
# 3. 

Ejercicios con transpose

In [34]:
# 4. Utiliza el array 3D del ejercicio 2 de reshape. 
# Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
array_7_transpose = np.transpose(array_7, (2, 1, 0))
print(array_7)
print(array_7_transpose)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


In [ ]:
# 5. 

Preguntas teóricas:

1. ¿Qué diferencia existe entre el reshape y el transpose?
reshape cambia la forma del array y transpose transpone las dimensiones del array

2. ¿Y entre el transpose y el swapaxes?
swapaxes intercambia dos ejes pero no puedes especificar el orden, con transpose sí puedes

Funciones Aritméticas y Estadísticas

In [37]:
# 1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) 
# cuyos valores solo tengan 1 decimal.
array_8 = np.random.rand(2,3,5).round(1)
array_8


array([[[0.3, 0.3, 0.9, 0.7, 0.7],
        [0.6, 0.4, 0.5, 0.2, 0.1],
        [0.9, 0.4, 0.6, 0.6, 0.3]],

       [[1. , 0.8, 0.3, 0.8, 0.3],
        [0.9, 0.6, 0.8, 0.4, 0.9],
        [0.6, 1. , 0.3, 0.3, 0.1]]])

In [14]:
# 2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
# Si el valor del array es igual que la media, se reemplaza por "A".
# Si el valor del array es mayor que la media, se reemplaza por "B".
# Si el valor del array es menor que la media, se reemplaza por "C".
# Si el valor es igual que el máximo, se reemplaza por "D".
# Si el valor es igual que el mínimo, se reemplaza por "E".
# AMBAS